name: Feature Branch Pipeline

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Test and build native image
        run: ./mvnw -B clean verify -Dnative -Dquarkus.native.container-build=true
